### ISSUE TITLE
KeyError: 'actions'

### ISSUE THREAD

**Issue by SeekPoint** [momohuang/FusionNet-NLI#2]
python3  prepro.py
03/07/2018 03:08:36 start data preparing... (using 8 threads)
03/07/2018 03:09:38 glove loaded.
03/07/2018 03:09:44 train jsonline data flattened.
03/07/2018 03:57:14 All tokens for training are obtained.
03/07/2018 03:59:35 features for training is generated.
03/07/2018 03:59:38 vocab 80033/88742 OOV 42624/13374314 (0.3187%)
Traceback (most recent call last):
  File "prepro.py", line 107, in <module>
    vocab_ent = [''] + nlp.entity.cfg[u'actions']['1']
KeyError: 'actions'

**Comment by hsinyuan-huang** [comment]
Hi @loveJasmine,

I think it is because you are using the latest spaCy rather than v1.x.
You can also use the provided Docker image to prevent version problems altogether.

**Comment by SeekPoint** [comment]
yes, fixed it
