### ISSUE TITLE
what the opt for ‘use_cove'

### ISSUE THREAD

**Issue by SeekPoint** [momohuang/FusionNet-NLI#3]
03/07/2018 08:58:14 updates[ 12161] train loss[0.82523] remaining[0:00:37]
03/07/2018 08:58:36 updates[ 12241] train loss[0.82464] remaining[0:00:10]
//FusionModel/layers.py:184: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_flat = F.softmax(scores.view(-1, x2.size(1)))
//FusionModel/layers.py:211: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha = F.softmax(scores)
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main()
  File "train.py", line 141, in main
    model.setup_eval_embed(dev_embedding)
  File "//FusionModel/model.py", line 129, in setup_eval_embed
    if self.opt['use_cove']:
KeyError: 'use_cove'

**Comment by hsinyuan-huang** [comment]
Hi @loveJasmine,

"use_cove" is used for an experiment in the paper.
In this repo, I always set "use_cove" as true but forgot to remove this one.
Thanks for pointing this out, I have pushed the latest version without this bug.

**Comment by SeekPoint** [comment]
it works
