### ISSUE TITLE
Got error when running prepro.py

### ISSUE THREAD

**Issue by HolyB** [momohuang/FusionNet-NLI#9]
Traceback (most recent call last):
  File "/Users/FusionNet-NLI/prepro.py", line 106, in <module>
    vocab_ent = [''] + nlp.entity.cfg[u'actions'][1]

**Comment by midori1** [comment]
Your SpaCy version may not meet the requirements.

**Comment by HolyB** [comment]
Which version should be needed? I used spacy==1.10.1

**Comment by midori1** [comment]
That's a little wired... In fact, I didn't try that version. Instead, I use spacy in 2.0 and count the POS and NER by a counter like the one counts the words.

**Comment by hsinyuan-huang** [comment]
Hi!

I have modified the code so it works with the latest spaCy.
